key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
offset.flush.interval.ms=10000

# LOCALHOST CONFIGURATION
# bootstrap.servers=localhost:9092
bootstrap.servers=kafka-227b8376-fernando-spizzca.c.aivencloud.com:27517
security.protocol=SSL
ssl.protocol=TLS
ssl.key.password=AVNS_QT5n5bcsLRmCv206GLP
ssl.keystore.location=D:\OneDrive\Documentos\Cursos\Kafka\certificados_aiven/client.keystore.p12
ssl.keystore.password=AVNS_QT5n5bcsLRmCv206GLP
ssl.keystore.type=PKCS12
ssl.truststore.location=D:\OneDrive\Documentos\Cursos\Kafka\certificados_aiven/client.truststore.jks
ssl.truststore.password=AVNS_QT5n5bcsLRmCv206GLP
ssl.truststore.type=JKS

offset.storage.file.filename=/tmp/connect.offsets
plugin.path=/home/ferhs/kafka_2.13-4.1.1/connectors,